import { NextResponse } from "next/server";
import { getCompanyContext } from "@/lib/company";
export const dynamic = "force-dynamic";

type Body = { id?: number|string; date?: string; seller?: string; description?: string; amount?: number|string; payment?: string; invoiceNumber?: string; invoiceImage?: string; notes?: string };
const digits=(v:string)=>v.replace(/[۰-۹]/g,d=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(d))).replace(/[٠-٩]/g,d=>String("٠١٢٣٤٥٦٧٨٩".indexOf(d)));
const amount=(v:unknown)=>{const n=typeof v==="number"?v:Number(digits(String(v??"")).replace(/[,٬]/g,""));return Number.isFinite(n)?n:0};
const date=(v:unknown)=>{if(!v)return null;const m=/^(\d{4})[-/.](\d{1,2})[-/.](\d{1,2})$/.exec(digits(String(v).trim()));return m?`${m[1]}-${m[2].padStart(2,"0")}-${m[3].padStart(2,"0")}`:null};
const map=(x:any)=>({id:x.id,date:x.date??x.purchase_date??null,seller:x.seller??x.supplier??"",description:x.description??x.title??"",amount:amount(x.amount),payment:x.payment??"",invoiceNumber:x.invoice_number??"",invoiceImage:x.invoice_image??"",notes:x.notes??"",status:x.status??"ثبت شده",createdAt:x.created_at??null});
const fields=`id,date,seller,description,amount,payment,invoice_number,invoice_image,notes,status,title,supplier,purchase_date,created_at`;
async function ctx(){const c=await getCompanyContext();if(!c.companyId)return null;return c;}

export async function GET(){try{const c=await ctx();if(!c)return NextResponse.json({success:false,message:"برای مشاهده اطلاعات وارد حساب شوید."},{status:401});const {data,error}=await c.supabase.from("purchases").select(fields).eq("company_id",c.companyId).order("id",{ascending:false});if(error)throw error;return NextResponse.json({success:true,data:(data||[]).map(map)},{headers:{"Cache-Control":"private, no-store"}})}catch(e){return NextResponse.json({success:false,message:"خطا در دریافت خریدها",error:e instanceof Error?e.message:"خطای نامشخص"},{status:500})}}

export async function POST(req:Request){try{const c=await ctx();if(!c)return NextResponse.json({success:false,message:"دسترسی غیرمجاز"},{status:401});const b:Body=await req.json();const seller=String(b.seller??"").trim(),description=String(b.description??"").trim(),a=amount(b.amount),d=date(b.date)||new Date().toISOString().slice(0,10);if(!seller||!description||a<=0)return NextResponse.json({success:false,message:"فروشنده، شرح خرید و مبلغ صحیح الزامی است."},{status:400});const {data,error}=await c.supabase.from("purchases").insert({company_id:c.companyId,title:description,supplier:seller,category:"",purchase_date:d,date:d,seller,description,amount:a,payment:String(b.payment??"کارت"),invoice_number:String(b.invoiceNumber??""),invoice_image:String(b.invoiceImage??""),notes:String(b.notes??""),status:"ثبت شده"}).select(fields).single();if(error)throw error;return NextResponse.json({success:true,message:"خرید با موفقیت ذخیره شد.",data:map(data)},{status:201})}catch(e){return NextResponse.json({success:false,message:"خطا در ذخیره خرید",error:e instanceof Error?e.message:"خطای نامشخص"},{status:500})}}

export async function PUT(req:Request){try{const c=await ctx();if(!c)return NextResponse.json({success:false,message:"دسترسی غیرمجاز"},{status:401});const b:Body=await req.json(),id=Number(b.id),seller=String(b.seller??"").trim(),description=String(b.description??"").trim(),a=amount(b.amount),d=date(b.date)||new Date().toISOString().slice(0,10);if(!Number.isInteger(id)||id<=0||!seller||!description||a<=0)return NextResponse.json({success:false,message:"اطلاعات ویرایش صحیح نیست."},{status:400});const {data:existing,error:findError}=await c.supabase.from("purchases").select("id").eq("id",id).eq("company_id",c.companyId).maybeSingle();if(findError)throw findError;if(!existing)return NextResponse.json({success:false,message:"خرید پیدا نشد."},{status:404});const {data,error}=await c.supabase.from("purchases").update({title:description,supplier:seller,category:"",purchase_date:d,date:d,seller,description,amount:a,payment:String(b.payment??"کارت"),invoice_number:String(b.invoiceNumber??""),invoice_image:b.invoiceImage===undefined?undefined:String(b.invoiceImage??""),notes:String(b.notes??""),status:"ثبت شده"}).eq("id",id).eq("company_id",c.companyId).select(fields).single();if(error)throw error;return NextResponse.json({success:true,message:"خرید با موفقیت ویرایش شد.",data:map(data)})}catch(e){return NextResponse.json({success:false,message:"خطا در ویرایش خرید",error:e instanceof Error?e.message:"خطای نامشخص"},{status:500})}}

export async function DELETE(req:Request){try{const c=await ctx();if(!c)return NextResponse.json({success:false,message:"دسترسی غیرمجاز"},{status:401});const b:Body=await req.json(),id=Number(b.id);if(!Number.isInteger(id)||id<=0)return NextResponse.json({success:false,message:"شناسه خرید صحیح نیست."},{status:400});const {data:existing,error:findError}=await c.supabase.from("purchases").select("id,invoice_image").eq("id",id).eq("company_id",c.companyId).maybeSingle();if(findError)throw findError;if(!existing)return NextResponse.json({success:false,message:"خرید پیدا نشد."},{status:404});const {error}=await c.supabase.from("purchases").delete().eq("id",id).eq("company_id",c.companyId);if(error)throw error;return NextResponse.json({success:true,message:"خرید با موفقیت حذف شد.",image:existing.invoice_image||null})}catch(e){return NextResponse.json({success:false,message:"خطا در حذف خرید",error:e instanceof Error?e.message:"خطای نامشخص"},{status:500})}}
