"use client";
import { FormEvent, ReactNode, useEffect, useMemo, useState } from "react";
type Purchase={id:number;date:string;seller:string;description:string;amount:number;payment:string;invoiceNumber?:string;invoiceImage?:string;notes?:string;status:string};
type Payment={id:number;date:string;title:string;amount:number;method:string;receiptImage?:string};
type Form={date:string;seller:string;description:string;amount:string;payment:string;invoiceNumber:string;notes:string;invoiceImage:string};
const today=()=>new Date().toISOString().slice(0,10); const digits=(v:string)=>v.replace(/[۰-۹]/g,d=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(d))).replace(/[٠-٩]/g,d=>String("٠١٢٣٤٥٦٧٨٩".indexOf(d))); const money=(v:number)=>new Intl.NumberFormat("fa-IR").format(Math.round(v||0));
function div(a:number,b:number){return Math.floor(a/b)} function mod(a:number,b:number){return a-Math.floor(a/b)*b}
function g2j(g:string){const [gy,gm,gd]=g.split("-").map(Number);if(!gy||!gm||!gd)return"";let n=365*(gy-1600)+div(gy-1600+3,4)-div(gy-1600+99,100)+div(gy-1600+399,400);const md=[31,28,31,30,31,30,31,31,30,31,30,31];for(let i=0;i<gm-1;i++)n+=md[i];if(gm>2&&gy%4===0&&(gy%100!==0||gy%400===0))n++;n+=gd-1;let j=n-79,jnp=div(j,12053);j=mod(j,12053);let jy=979+33*jnp+4*div(j,1461);j=mod(j,1461);if(j>=366){jy+=div(j-1,365);j=mod(j-1,365)}const jm=j<186?1+div(j,31):7+div(j-186,30),jd=1+mod(j,jm<=6?31:30);return`${jy}/${String(jm).padStart(2,"0")}/${String(jd).padStart(2,"0")}`}
function j2g(jv:string){const v=digits(jv).replace(/[-.]/g,"/").replace(/\s/g,"");const m=v.match(/^(\d{4})\/(\d{1,2})\/(\d{1,2})$/);if(!m)return null;const jy=+m[1],jm=+m[2],jd=+m[3];if(jy<1200||jy>1600||jm<1||jm>12||jd<1||jd>(jm<=6?31:30))return null;let j=365*(jy-979)+div(jy-979,33)*8+div((mod(jy-979,33)+3),4)+jd-1;j+=jm<7?(jm-1)*31:(jm-1)*30+6;j+=355668;let gy=400*div(j,146097);j=mod(j,146097);if(j>36524){gy+=100*div(--j,36524);j=mod(j,36524);if(j>=365)j++}gy+=4*div(j,1461);j=mod(j,1461);if(j>365){gy+=div(j-1,365);j=mod(j,365)}const gd=j+1,leap=gy%4===0&&(gy%100!==0||gy%400===0),days=[31,leap?29:28,31,leap?30:30,31,30,31,31,30,31,30,31];let gm=1,r=gd;while(r>days[gm-1]){r-=days[gm-1];gm++}return`${gy}-${String(gm).padStart(2,"0")}-${String(r).padStart(2,"0")}`}
const empty=():Form=>({date:today(),seller:"",description:"",amount:"",payment:"کارت",invoiceNumber:"",notes:"",invoiceImage:""});
async function api(url:string,options?:RequestInit){const r=await fetch(url,{cache:"no-store",...options});const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw new Error(d.message||"خطا در ارتباط با سرور");return d}
function PersianDateInput({value,onChange}:{value:string;onChange:(v:string)=>void}){const[t,setT]=useState(g2j(value));useEffect(()=>setT(g2j(value)),[value]);return <input required type="text" inputMode="numeric" dir="ltr" value={t} onChange={e=>{const n=digits(e.target.value).replace(/[^0-9/]/g,"");setT(n);const g=j2g(n);if(g)onChange(g)}} onBlur={()=>setT(g2j(value))} placeholder="۱۴۰۵/۰۶/۱۲" className="input text-center tracking-wider" aria-label="تاریخ شمسی"/>}
export default function Home(){
 const[tab,setTab]=useState("dashboard"),[purchases,setPurchases]=useState<Purchase[]>([]),[payments,setPayments]=useState<Payment[]>([]),[company,setCompany]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[q,setQ]=useState(""),[form,setForm]=useState(empty()),[editing,setEditing]=useState<Purchase|null>(null),[payment,setPayment]=useState({date:today(),title:"",amount:"",method:"کارت"});
 const[financial,setFinancial]=useState<Record<string,any[]>>({suppliers:[],categories:[],accounts:[],budgets:[],checks:[],purchase_items:[]});
 const loadFinancial=async()=>{const types=Object.keys(financial);const out:Record<string,any[]>={};await Promise.all(types.map(async t=>{const d=await api(`/api/financial?type=${t}`);out[t]=d.data||[]}));setFinancial(out)};
 const load=async()=>{setLoading(true);setError("");try{const[c,p,v]=await Promise.all([api("/api/company"),api("/api/purchases"),api("/api/payments")]);setCompany(c.data?.name||"");setPurchases(p.data||[]);setPayments(v.data||[]);await loadFinancial()}catch(e){setError(e instanceof Error?e.message:"خطا در دریافت اطلاعات")}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const total=purchases.reduce((s,x)=>s+Number(x.amount||0),0),paid=payments.reduce((s,x)=>s+Number(x.amount||0),0),balance=total-paid;
 const filtered=useMemo(()=>{const x=digits(q).toLowerCase();return x?purchases.filter(p=>`${p.seller} ${p.description} ${p.invoiceNumber||""}`.toLowerCase().includes(x)):purchases},[purchases,q]);
 const suppliers=useMemo(()=>{const m=new Map<string,number>();purchases.forEach(p=>m.set(p.seller,(m.get(p.seller)||0)+Number(p.amount||0)));return Array.from(m.entries()).sort((a,b)=>b[1]-a[1])},[purchases]);
 const methods=useMemo(()=>{const m=new Map<string,number>();purchases.forEach(p=>m.set(p.payment,(m.get(p.payment)||0)+Number(p.amount||0)));return Array.from(m.entries()).sort((a,b)=>b[1]-a[1])},[purchases]);
 const upload=async(file:File)=>{const f=new FormData();f.append("file",file);const d=await api("/api/upload",{method:"POST",body:f});return String(d.url||"")};
 const savePurchase=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{await api("/api/purchases",{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,id:editing?.id,amount:digits(form.amount).replace(/[,٬]/g,"")})});setEditing(null);setForm(empty());await load();setTab("purchases")}catch(e){setError(e instanceof Error?e.message:"ثبت خرید ناموفق بود")}finally{setBusy(false)}};
 const remove=async(id:number)=>{if(!confirm("این خرید حذف شود؟"))return;setBusy(true);try{await api("/api/purchases",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});await load()}catch(e){setError(e instanceof Error?e.message:"حذف ناموفق بود")}finally{setBusy(false)}};
 const savePayment=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{await api("/api/payments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...payment,amount:digits(payment.amount).replace(/[,٬]/g,"")})});setPayment({date:today(),title:"",amount:"",method:"کارت"});await load()}catch(e){setError(e instanceof Error?e.message:"ثبت پرداخت ناموفق بود")}finally{setBusy(false)}};
 const edit=(p:Purchase)=>{setEditing(p);setForm({date:p.date||today(),seller:p.seller||"",description:p.description||"",amount:String(p.amount||""),payment:p.payment||"کارت",invoiceNumber:p.invoiceNumber||"",notes:p.notes||"",invoiceImage:p.invoiceImage||""});setTab("invoices")};
 const more=[['reports','📊','گزارش‌ها','تحلیل خرید و پرداخت'],['finance','💰','مرکز مالی','حساب‌ها، بودجه، چک و تأمین‌کنندگان'],['suppliers','👥','فروشندگان','مانده و مجموع خرید'],['debts','⚠️','بدهی‌ها و سررسید','وضعیت بدهی شرکت'],['categories','🏷️','دسته‌بندی هزینه‌ها','مدیریت گروه هزینه‌ها'],['accounts','🏦','حساب‌ها و صندوق','روش‌های پرداخت و حساب‌ها'],['checks','🧾','چک‌ها','چک‌های پرداختی و دریافتی'],['members','🔐','اعضای شرکت','مدیریت دسترسی کاربران'],['settings','⚙️','تنظیمات','تنظیمات حساب شرکت']];
 return <main dir="rtl" className="min-h-screen bg-slate-50 text-slate-900"><header className="sticky top-0 z-40 border-b bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3"><div><p className="text-xs text-slate-500">مدیریت مالی شرکت</p><h1 className="text-lg font-black">{company||"خرید و هزینه شرکت"}</h1></div><div className="flex gap-2"><button onClick={load} className="rounded-xl border px-3 py-2 text-sm font-bold">↻</button><form action="/api/auth/signout" method="post"><button className="rounded-xl border px-3 py-2 text-sm font-bold">خروج</button></form></div></div></header>
 <section className="mx-auto max-w-6xl space-y-4 px-4 pb-28 pt-5">{error&&<div className="rounded-2xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>}
 {tab==="dashboard"&&<><div className="rounded-3xl bg-slate-900 p-6 text-white"><p className="text-sm text-slate-300">مانده حساب شرکت</p><b className="mt-2 block text-3xl">{money(Math.abs(balance))}</b><p className="mt-1 text-sm text-slate-300">{balance>=0?"مانده بدهی خریدها":"مازاد پرداخت‌ها"}</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Card t="کل خریدها" v={money(total)}/><Card t="کل پرداخت‌ها" v={money(paid)}/><Card t="مانده" v={money(Math.abs(balance))}/><Card t="تعداد خرید" v={purchases.length.toLocaleString("fa-IR")}/></div><div className="rounded-2xl bg-white p-4 ring-1 ring-slate-200"><h2 className="font-black">دسترسی سریع</h2><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-5">{[['finance','💰 مرکز مالی'],['reports','📊 گزارش‌ها'],['suppliers','👥 فروشندگان'],['debts','⚠️ بدهی‌ها'],['accounts','🏦 حساب‌ها']].map(([id,l])=><button key={id} onClick={()=>setTab(id)} className="rounded-xl border p-3 text-sm font-bold">{l}</button>)}</div></div></>}
 {tab==="finance"&&<FinanceCenter financial={financial} money={money} onRefresh={loadFinancial}/>} 
 {tab==="purchases"&&<><div className="flex items-center justify-between"><h2 className="text-xl font-black">خریدها</h2><button onClick={()=>{setEditing(null);setForm(empty());setTab("invoices")}} className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white">＋ ثبت خرید</button></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="🔎 جستجوی فروشنده یا شرح" className="w-full rounded-xl border bg-white px-4 py-3"/>{loading?<Loading/>:<div className="grid gap-3 sm:grid-cols-2">{filtered.map(p=><article key={p.id} className="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><div className="flex justify-between gap-3"><div><b>{p.seller}</b><p className="text-xs text-slate-500">{g2j(p.date)} • {p.payment}</p></div><b>{money(p.amount)}</b></div><p className="mt-2 text-sm">{p.description}</p>{p.invoiceImage&&<img src={p.invoiceImage} alt="فاکتور" className="mt-3 max-h-48 w-full rounded-xl object-contain"/>}<div className="mt-3 flex gap-2"><button onClick={()=>edit(p)} className="flex-1 rounded-xl bg-slate-900 py-2 text-sm font-bold text-white">ویرایش</button><button onClick={()=>remove(p.id)} className="rounded-xl border border-red-200 px-4 py-2 text-sm font-bold text-red-600">حذف</button></div></article>)}</div>}</>}
 {tab==="invoices"&&<form onSubmit={savePurchase} className="space-y-3 rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex justify-between"><h2 className="text-xl font-black">{editing?"ویرایش خرید":"ثبت خرید جدید"}</h2>{editing&&<button type="button" onClick={()=>{setEditing(null);setTab("purchases")}} className="text-sm font-bold">انصراف</button>}</div><Field l="تاریخ خرید"><PersianDateInput value={form.date} onChange={date=>setForm(f=>({...f,date}))}/></Field><Field l="نام فروشنده"><input required value={form.seller} onChange={e=>setForm(f=>({...f,seller:e.target.value}))} className="input"/></Field><Field l="شرح خرید"><input required value={form.description} onChange={e=>setForm(f=>({...f,description:e.target.value}))} className="input"/></Field><Field l="مبلغ"><input required inputMode="decimal" value={form.amount} onChange={e=>setForm(f=>({...f,amount:e.target.value}))} className="input"/></Field><div className="grid gap-3 sm:grid-cols-2"><Field l="روش پرداخت"><select value={form.payment} onChange={e=>setForm(f=>({...f,payment:e.target.value}))} className="input"><option>کارت</option><option>نقدی</option><option>حساب بانکی</option><option>چک</option><option>نسیه</option></select></Field><Field l="شماره فاکتور"><input value={form.invoiceNumber} onChange={e=>setForm(f=>({...f,invoiceNumber:e.target.value}))} className="input"/></Field></div><Field l="یادداشت"><textarea value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))} className="input min-h-24"/></Field><Field l="تصویر فاکتور"><input type="file" accept="image/*" capture="environment" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{const url=await upload(f);setForm(x=>({...x,invoiceImage:url}))}catch(err){setError(err instanceof Error?err.message:"آپلود عکس ناموفق بود")}}} className="w-full rounded-xl border border-dashed p-3"/>{form.invoiceImage&&<img src={form.invoiceImage} alt="پیش‌نمایش" className="mt-2 max-h-64 w-full rounded-xl object-contain"/>}</Field><button disabled={busy} className="w-full rounded-xl bg-slate-900 py-3.5 font-black text-white">{busy?"در حال ذخیره…":editing?"ذخیره تغییرات":"ثبت خرید"}</button></form>}
 {tab==="payments"&&<><h2 className="text-xl font-black">پرداخت‌ها</h2><div className="grid gap-3 sm:grid-cols-2">{payments.map(p=><article key={p.id} className="rounded-2xl bg-white p-4 ring-1 ring-slate-200"><div className="flex justify-between"><b>{p.title}</b><b>{money(p.amount)}</b></div><p className="mt-1 text-xs text-slate-500">{g2j(p.date)} • {p.method}</p></article>)}</div><form onSubmit={savePayment} className="space-y-3 rounded-2xl bg-white p-4 ring-1 ring-slate-200"><h3 className="font-black">ثبت پرداخت</h3><PersianDateInput value={payment.date} onChange={date=>setPayment(f=>({...f,date}))}/><input required value={payment.title} onChange={e=>setPayment(f=>({...f,title:e.target.value}))} className="input" placeholder="عنوان پرداخت"/><input required inputMode="decimal" value={payment.amount} onChange={e=>setPayment(f=>({...f,amount:e.target.value}))} className="input" placeholder="مبلغ"/><select value={payment.method} onChange={e=>setPayment(f=>({...f,method:e.target.value}))} className="input"><option>کارت</option><option>نقدی</option><option>حساب بانکی</option><option>چک</option></select><button disabled={busy} className="w-full rounded-xl bg-slate-900 py-3 font-bold text-white">ثبت پرداخت</button></form></>}
 {tab==="reports"&&<Panel title="گزارش‌های مالی"><div className="grid grid-cols-2 gap-3"><Card t="مجموع خرید" v={money(total)}/><Card t="مجموع پرداخت" v={money(paid)}/><Card t="مانده" v={money(Math.abs(balance))}/><Card t="تعداد فاکتور" v={purchases.length.toLocaleString("fa-IR")}/></div><h3 className="mt-5 font-black">روش‌های پرداخت</h3>{methods.length?<div className="mt-2 space-y-2">{methods.map(([m,v])=><Row key={m} a={m} b={money(v)}/>)}</div>:<Empty/>}</Panel>}
 {tab==="suppliers"&&<Panel title="فروشندگان"><p className="text-sm text-slate-500">مجموع خرید ثبت‌شده برای هر فروشنده</p><div className="mt-3">{suppliers.length?suppliers.map(([s,v])=><Row key={s} a={s} b={money(v)}/>):<Empty/>}</div></Panel>}
 {tab==="debts"&&<Panel title="بدهی‌ها و سررسید"><div className="rounded-2xl bg-amber-50 p-4"><p className="text-sm font-bold text-amber-800">مانده بدهی فعلی</p><b className="mt-1 block text-2xl">{money(Math.max(balance,0))}</b></div><p className="mt-4 text-sm text-slate-500">سررسیدهای ثبت‌شده در مرکز مالی قابل مدیریت هستند.</p></Panel>}
 {tab==="categories"&&<Panel title="دسته‌بندی هزینه‌ها"><SimpleList items={financial.categories} label="name" money={money}/></Panel>}
 {tab==="accounts"&&<Panel title="حساب‌ها و صندوق"><SimpleList items={financial.accounts} label="name" money={money} amountKey="opening_balance"/></Panel>}
 {tab==="checks"&&<Panel title="چک‌ها"><SimpleList items={financial.checks} label="check_no" money={money} amountKey="amount"/></Panel>}
 {tab==="members"&&<Panel title="اعضای شرکت"><p className="text-sm text-slate-500">مدیریت اعضا و سطح دسترسی در زیرساخت امن شرکت فعال است.</p><div className="mt-3 rounded-xl bg-slate-50 p-4 text-sm">نقش‌ها: مالک، مدیر، عضو</div></Panel>}
 {tab==="settings"&&<Panel title="تنظیمات"><p className="text-sm text-slate-500">شرکت فعال</p><b className="mt-1 block">{company}</b></Panel>}
 {tab==="more"&&<div className="grid gap-3 sm:grid-cols-2">{more.map(([id,icon,title,desc])=><button key={id} onClick={()=>setTab(id)} className="rounded-2xl bg-white p-4 text-right ring-1 ring-slate-200"><span className="text-2xl">{icon}</span><b className="mt-2 block">{title}</b><span className="text-xs text-slate-500">{desc}</span></button>)}</div>}
 </section><nav className="fixed bottom-0 left-0 right-0 z-50 border-t bg-white/95 pb-[env(safe-area-inset-bottom)]"><div className="mx-auto grid max-w-2xl grid-cols-5 p-1">{[["dashboard","داشبورد","⌂"],["purchases","خریدها","▣"],["invoices","ثبت خرید","＋"],["payments","پرداخت‌ها","◉"],["more","بیشتر","•••"]].map(([id,l,i])=><button key={id} onClick={()=>id==="invoices"?(setEditing(null),setForm(empty()),setTab("invoices")):setTab(id)} className={`flex min-h-14 flex-col items-center justify-center rounded-xl text-[11px] font-bold ${tab===id?"bg-slate-100":"text-slate-500"}`}><span className="text-lg">{i}</span>{l}</button>)}</div></nav></main>}
function FinanceCenter({financial,money,onRefresh}:{financial:Record<string,any[]>;money:(v:number)=>string;onRefresh:()=>Promise<void>}){const cards=[['suppliers','👥','تأمین‌کنندگان',financial.suppliers.length],['categories','🏷️','دسته‌بندی‌ها',financial.categories.length],['accounts','🏦','حساب‌ها و صندوق',financial.accounts.length],['budgets','💰','بودجه‌ها',financial.budgets.length],['checks','🧾','چک‌ها',financial.checks.length],['purchase_items','📦','ریز اقلام فاکتور',financial.purchase_items.length]];return <div className="space-y-4"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">مرکز مالی</h2><p className="text-sm text-slate-500">همه ابزارهای مالی شرکت در یک صفحه</p></div><button onClick={onRefresh} className="rounded-xl border px-3 py-2 text-sm font-bold">↻ بروزرسانی</button></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{cards.map(([id,icon,title,count])=><div key={id} className="rounded-2xl bg-white p-4 ring-1 ring-slate-200"><span className="text-2xl">{icon}</span><b className="mt-2 block">{title}</b><span className="text-xs text-slate-500">{Number(count).toLocaleString('fa-IR')} مورد</span></div>)}</div><div className="rounded-2xl bg-white p-4 ring-1 ring-slate-200"><h3 className="font-black">خلاصه مالی</h3><div className="mt-3 grid gap-2 sm:grid-cols-3"><Row a="بودجه ثبت‌شده" b={money(financial.budgets.reduce((s,x)=>s+Number(x.amount||0),0))}/><Row a="ارزش چک‌ها" b={money(financial.checks.reduce((s,x)=>s+Number(x.amount||0),0))}/><Row a="تأمین‌کنندگان" b={Number(financial.suppliers.length).toLocaleString('fa-IR')}/></div></div></div>}
function Card({t,v}:{t:string;v:string}){return <div className="rounded-2xl bg-white p-4 ring-1 ring-slate-200"><p className="text-xs text-slate-500">{t}</p><b className="mt-2 block text-lg">{v}</b></div>}
function Panel({title,children}:{title:string;children:ReactNode}){return <div className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="text-xl font-black">{title}</h2><div className="mt-4">{children}</div></div>}
function Row({a,b}:{a:string;b:string}){return <div className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><span className="font-bold">{a}</span><b>{b}</b></div>}
function SimpleList({items,label,money,amountKey="opening_balance"}:{items:any[];label:string;money:(v:number)=>string;amountKey?:string}){return items.length?<div className="space-y-2">{items.map(x=><Row key={x.id} a={String(x[label]||"—")} b={x[amountKey]!=null?money(Number(x[amountKey])):"ثبت‌شده"}/>)}</div>:<Empty/>}
function Empty({text="هنوز اطلاعاتی ثبت نشده است."}:{text?:string}){return <div className="rounded-2xl bg-slate-50 p-6 text-center text-sm text-slate-500">{text}</div>}
function Loading(){return <div className="rounded-2xl bg-white p-8 text-center text-sm text-slate-500">در حال دریافت…</div>}
function Field({l,children}:{l:string;children:ReactNode}){return <label className="block"><span className="mb-1 block text-xs font-bold text-slate-600">{l}</span>{children}</label>}
