import { NextResponse } from "next/server";
import { getCompanyContext } from "@/lib/company";
export const dynamic = "force-dynamic";
type Body={id?:number|string;date?:string;title?:string;amount?:number|string;method?:string;description?:string;receiptImage?:string;notes?:string};
const digits=(v:string)=>v.replace(/[۰-۹]/g,d=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(d))).replace(/[٠-٩]/g,d=>String("٠١٢٣٤٥٦٧٨٩".indexOf(d)));const amount=(v:unknown)=>{const n=typeof v==="number"?v:Number(digits(String(v??"")).replace(/[,٬]/g,""));return Number.isFinite(n)?n:0};const date=(v:unknown)=>{if(!v)return null;const m=/^(\d{4})[-/.](\d{1,2})[-/.](\d{1,2})$/.exec(digits(String(v).trim()));return m?`${m[1]}-${m[2].padStart(2,"0")}-${m[3].padStart(2,"0")}`:null};const map=(x:any)=>({id:x.id,date:x.date??x.payment_date??null,title:x.title??"",amount:amount(x.amount),method:x.method??x.payment_method??"",description:x.description??"",receiptImage:x.receipt_image??"",notes:x.notes??"",createdAt:x.created_at??null});const fields=`id,date,title,amount,method,description,receipt_image,notes,payment_date,payment_method,created_at`;
async function ctx(){const c=await getCompanyContext();return c.companyId?c:null}
export async function GET(){try{const c=await ctx();if(!c)return NextResponse.json({success:false,message:"برای مشاهده اطلاعات وارد حساب شوید."},{status:401});const {data,error}=await c.supabase.from("payments").select(fields).eq("company_id",c.companyId).order("id",{ascending:false});if(error)throw error;return NextResponse.json({success:true,data:(data||[]).map(map)},{headers:{"Cache-Control":"private, no-store"}})}catch(e){return NextResponse.json({success:false,message:"خطا در دریافت واریزها",error:e instanceof Error?e.message:"خطای نامشخص"},{status:500})}}
export async function POST(req:Request){try{const c=await ctx();if(!c)return NextResponse.json({success:false,message:"دسترسی غیرمجاز"},{status:401});const b:Body=await req.json(),title=String(b.title??"").trim(),a=amount(b.amount),d=date(b.date)||new Date().toISOString().slice(0,10);if(!title||a<=0)return NextResponse.json({success:false,message:"عنوان و مبلغ صحیح الزامی است."},{status:400});const method=String(b.method??"کارت");const {data,error}=await c.supabase.from("payments").insert({company_id:c.companyId,title,amount:a,date:d,payment_date:d,method,payment_method:method,description:String(b.description??""),receipt_image:String(b.receiptImage??""),notes:String(b.notes??"")}).select(fields).single();if(error)throw error;return NextResponse.json({success:true,message:"واریز با موفقیت ذخیره شد.",data:map(data)},{status:201})}catch(e){return NextResponse.json({success:false,message:"خطا در ذخیره واریز",error:e instanceof Error?e.message:"خطای نامشخص"},{status:500})}}
export async function PUT(req:Request){try{const c=await ctx();if(!c)return NextResponse.json({success:false,message:"دسترسی غیرمجاز"},{status:401});const b:Body=await req.json(),id=Number(b.id),title=String(b.title??"").trim(),a=amount(b.amount),d=date(b.date)||new Date().toISOString().slice(0,10);if(!Number.isInteger(id)||id<=0||!title||a<=0)return NextResponse.json({success:false,message:"اطلاعات ویرایش صحیح نیست."},{status:400});const {data:existing,error:findError}=await c.supabase.from("payments").select("id").eq("id",id).eq("company_id",c.companyId).maybeSingle();if(findError)throw findError;if(!existing)return NextResponse.json({success:false,message:"واریز پیدا نشد."},{status:404});const method=String(b.method??"کارت");const {data,error}=await c.supabase.from("payments").update({title,amount:a,date:d,payment_date:d,method,payment_method:method,description:String(b.description??""),receipt_image:b.receiptImage===undefined?undefined:String(b.receiptImage??""),notes:String(b.notes??"")}).eq("id",id).eq("company_id",c.companyId).select(fields).single();if(error)throw error;return NextResponse.json({success:true,message:"واریز با موفقیت ویرایش شد.",data:map(data)})}catch(e){return NextResponse.json({success:false,message:"خطا در ویرایش واریز",error:e instanceof Error?e.message:"خطای نامشخص"},{status:500})}}
export async function DELETE(req:Request){try{const c=await ctx();if(!c)return NextResponse.json({success:false,message:"دسترسی غیرمجاز"},{status:401});const b:Body=await req.json(),id=Number(b.id);if(!Number.isInteger(id)||id<=0)return NextResponse.json({success:false,message:"شناسه واریز صحیح نیست."},{status:400});const {data:existing,error:findError}=await c.supabase.from("payments").select("id,receipt_image").eq("id",id).eq("company_id",c.companyId).maybeSingle();if(findError)throw findError;if(!existing)return NextResponse.json({success:false,message:"واریز پیدا نشد."},{status:404});const {error}=await c.supabase.from("payments").delete().eq("id",id).eq("company_id",c.companyId);if(error)throw error;return NextResponse.json({success:true,message:"واریز با موفقیت حذف شد.",image:existing.receipt_image||null})}catch(e){return NextResponse.json({success:false,message:"خطا در حذف واریز",error:e instanceof Error?e.message:"خطای نامشخص"},{status:500})}}
