"use client";
import { useEffect, useMemo, useState } from "react";

type TypeId="suppliers"|"categories"|"accounts"|"budgets"|"checks"|"purchase_items";
const types:[TypeId,string,string][]=[
 ["suppliers","👥","تأمین‌کنندگان"],["categories","🏷️","دسته‌بندی هزینه‌ها"],["accounts","🏦","حساب‌ها و صندوق"],
 ["budgets","💰","بودجه‌بندی"],["checks","🧾","چک‌ها"],["purchase_items","📦","ریز اقلام فاکتور"]
];
const fields:Record<TypeId,string[]>={suppliers:["name","phone","contact","notes"],categories:["name","kind"],accounts:["name","kind","opening_balance"],budgets:["title","category","amount","start_date","end_date"],checks:["check_no","kind","party","amount","issue_date","due_date","status","notes"],purchase_items:["description","quantity","unit_price","purchase_id"]};
const pretty=(k:string)=>({name:"نام",phone:"تلفن",contact:"تماس",notes:"یادداشت",kind:"نوع",opening_balance:"موجودی اولیه",title:"عنوان",category:"دسته",amount:"مبلغ",start_date:"از تاریخ",end_date:"تا تاریخ",check_no:"شماره چک",party:"طرف حساب",issue_date:"تاریخ صدور",due_date:"سررسید",status:"وضعیت",description:"شرح",quantity:"تعداد",unit_price:"قیمت واحد",purchase_id:"شناسه خرید"} as Record<string,string>)[k]||k;
const money=(v:any)=>new Intl.NumberFormat("fa-IR").format(Number(v||0));
const blank=()=>({} as Record<string,string>);

export default function Financial(){
 const [type,setType]=useState<TypeId>("suppliers"),[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[form,setForm]=useState<Record<string,string>>(blank()),[editing,setEditing]=useState<number|null>(null);
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch(`/api/financial?type=${type}`,{cache:"no-store"});const d=await r.json();if(!r.ok||!d.success)throw Error(d.message||"خطا در دریافت اطلاعات");setRows(d.data||[])}catch(e:any){setError(e.message||"خطا")}finally{setLoading(false)}};
 useEffect(()=>{setForm(blank());setEditing(null);load()},[type]);
 const totals=useMemo(()=>({count:rows.length,amount:rows.reduce((s,r)=>s+Number(r.amount||0),0)}),[rows]);
 const save=async(e:any)=>{e.preventDefault();setBusy(true);setError("");try{const payload={type,...form};const r=await fetch("/api/financial",{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(editing?{...payload,id:editing}:payload)});const d=await r.json();if(!r.ok||!d.success)throw Error(d.message||"ثبت ناموفق");setForm(blank());setEditing(null);await load()}catch(e:any){setError(e.message||"ثبت ناموفق")}finally{setBusy(false)}};
 const del=async(id:number)=>{if(!confirm("این مورد حذف شود؟"))return;setBusy(true);setError("");try{const r=await fetch("/api/financial",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({type,id})});const d=await r.json();if(!r.ok||!d.success)throw Error(d.message||"حذف ناموفق");if(editing===id){setEditing(null);setForm(blank())}await load()}catch(e:any){setError(e.message||"حذف ناموفق")}finally{setBusy(false)}};
 const edit=(r:any)=>{const next:Record<string,string>={};fields[type].forEach(k=>next[k]=r[k]===null||r[k]===undefined?"":String(r[k]));setForm(next);setEditing(Number(r.id));window.scrollTo({top:0,behavior:"smooth"})};
 return <main dir="rtl" className="min-h-screen bg-slate-50 p-4 text-slate-900"><div className="mx-auto max-w-6xl">
  <header className="mb-4 flex items-center justify-between gap-3"><div><p className="text-xs text-slate-500">مرکز مالی</p><h1 className="text-2xl font-black">مدیریت مالی شرکت</h1></div><a href="/" className="rounded-xl border bg-white px-4 py-2 text-sm font-bold">← بازگشت</a></header>
  <div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-6">{types.map(([id,icon,name])=><button key={id} onClick={()=>setType(id)} className={`rounded-2xl p-3 text-sm font-bold ring-1 ${type===id?"bg-slate-900 text-white ring-slate-900":"bg-white ring-slate-200"}`}>{icon}<span className="mr-2">{name}</span></button>)}</div>
  <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><Stat title="تعداد" value={totals.count.toLocaleString("fa-IR")}/><Stat title="جمع مبلغ" value={money(totals.amount)}/><Stat title="بخش فعال" value={types.find(x=>x[0]===type)?.[2]||""}/><button onClick={load} className="rounded-2xl bg-white p-4 text-sm font-bold ring-1 ring-slate-200">↻ بروزرسانی</button></div>
  {error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>}
  <form onSubmit={save} className="mt-4 grid gap-3 rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:grid-cols-2 lg:grid-cols-4"><h2 className="sm:col-span-2 lg:col-span-4 text-lg font-black">{editing?"ویرایش":"ثبت"} {types.find(x=>x[0]===type)?.[2]}</h2>{fields[type].map(k=><label key={k} className="text-sm font-bold">{pretty(k)}<input required={["name","amount","title","check_no","description","purchase_id"].includes(k)} value={form[k]??""} onChange={e=>setForm(x=>({...x,[k]:e.target.value}))} type={k.includes("date")?"date":k.includes("amount")||["quantity","unit_price","purchase_id","opening_balance"].includes(k)?"number":"text"} className="mt-1 w-full rounded-xl border px-3 py-2"/></label>)}<div className="flex gap-2 sm:col-span-2 lg:col-span-4"><button disabled={busy} className="flex-1 rounded-xl bg-slate-900 py-3 font-bold text-white">{busy?(editing?"در حال ذخیره...":"در حال ثبت..."):(editing?"ذخیره تغییرات":"ثبت اطلاعات")}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(blank())}} className="rounded-xl border px-5 font-bold">انصراف</button>}</div></form>
  <section className="mt-4 rounded-3xl bg-white p-5 ring-1 ring-slate-200"><div className="mb-3 flex justify-between"><h2 className="font-black">اطلاعات ثبت‌شده</h2><span className="text-xs text-slate-500">{rows.length.toLocaleString("fa-IR")} مورد</span></div>{loading?<p>در حال دریافت...</p>:rows.length===0?<p className="text-sm text-slate-500">هنوز موردی ثبت نشده است.</p>:<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{rows.map(r=><article key={r.id} className="rounded-2xl border p-4"><div className="flex justify-between gap-2"><b>{r.name||r.title||r.check_no||r.description||(`شناسه ${r.id}`)}</b><div className="flex gap-3"><button onClick={()=>edit(r)} className="text-sm font-bold">ویرایش</button><button disabled={busy} onClick={()=>del(r.id)} className="text-sm font-bold text-red-600">حذف</button></div></div><div className="mt-2 space-y-1 text-xs text-slate-600">{fields[type].filter(k=>r[k]!==null&&r[k]!==undefined&&r[k]!=="").map(k=><p key={k}><b>{pretty(k)}:</b> {(["amount","opening_balance","unit_price"].includes(k)?money(r[k]):String(r[k]))}</p>)}</div></article>)}</div>}</section>
 </div></main>;
}
function Stat({title,value}:{title:string;value:string}){return <div className="rounded-2xl bg-white p-4 ring-1 ring-slate-200"><p className="text-xs text-slate-500">{title}</p><b className="mt-1 block text-lg">{value}</b></div>}
