"use client";
import { useEffect,useState } from "react";
const types=[['suppliers','👥','تأمین‌کنندگان'],['categories','🏷️','دسته‌بندی هزینه‌ها'],['accounts','🏦','حساب‌ها و صندوق'],['budgets','💰','بودجه‌بندی'],['checks','🧾','چک‌ها'],['purchase_items','📦','ریز اقلام فاکتور']];
const labels:any={suppliers:['نام','تلفن','تماس','یادداشت'],categories:['نام','نوع'],accounts:['نام','نوع','موجودی اولیه'],budgets:['عنوان','دسته','مبلغ','از تاریخ','تا تاریخ'],checks:['شماره چک','نوع','طرف حساب','مبلغ','تاریخ صدور','سررسید','وضعیت','یادداشت'],purchase_items:['شرح','تعداد','قیمت واحد','شناسه خرید']};
const fields:any={suppliers:['name','phone','contact','notes'],categories:['name','kind'],accounts:['name','kind','opening_balance'],budgets:['title','category','amount','start_date','end_date'],checks:['check_no','kind','party','amount','issue_date','due_date','status','notes'],purchase_items:['description','quantity','unit_price','purchase_id']};
const pretty=(k:string)=>({name:'نام',phone:'تلفن',contact:'تماس',notes:'یادداشت',kind:'نوع',opening_balance:'موجودی اولیه',title:'عنوان',category:'دسته',amount:'مبلغ',start_date:'از تاریخ',end_date:'تا تاریخ',check_no:'شماره چک',party:'طرف حساب',issue_date:'تاریخ صدور',due_date:'سررسید',status:'وضعیت',description:'شرح',quantity:'تعداد',unit_price:'قیمت واحد',purchase_id:'شناسه خرید'} as any)[k]||k;
const money=(v:any)=>new Intl.NumberFormat('fa-IR').format(Number(v||0));
export default function Financial(){const[type,setType]=useState('suppliers'),[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[form,setForm]=useState<any>({});
const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/financial?type='+type,{cache:'no-store'});const d=await r.json();if(!r.ok||!d.success)throw Error(d.message||'خطا');setRows(d.data||[])}catch(e:any){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{setForm({});load()},[type]);
const save=async(e:any)=>{e.preventDefault();setBusy(true);try{const r=await fetch('/api/financial',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,...form})});const d=await r.json();if(!r.ok||!d.success)throw Error(d.message||'ثبت ناموفق');setForm({});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
const del=async(id:number)=>{if(!confirm('حذف شود؟'))return;setBusy(true);try{await fetch('/api/financial',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,id})});await load()}finally{setBusy(false)}};
return <main dir="rtl" className="min-h-screen bg-slate-50 p-4 text-slate-900"><div className="mx-auto max-w-6xl"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs text-slate-500">مرکز مالی</p><h1 className="text-2xl font-black">مدیریت مالی شرکت</h1></div><a href="/" className="rounded-xl border bg-white px-4 py-2 text-sm font-bold">← بازگشت</a></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-6">{types.map(([id,icon,name])=><button key={id} onClick={()=>setType(id)} className={'rounded-2xl p-3 text-sm font-bold ring-1 '+(type===id?'bg-slate-900 text-white':'bg-white ring-slate-200')}>{icon}<span className="mr-2">{name}</span></button>)}</div>{error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>}<form onSubmit={save} className="mt-4 grid gap-3 rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:grid-cols-2 lg:grid-cols-4"><h2 className="sm:col-span-2 lg:col-span-4 text-lg font-black">ثبت {types.find(x=>x[0]===type)?.[2]}</h2>{fields[type].map((k:string)=><label key={k} className="text-sm font-bold">{pretty(k)}<input required={['name','amount','title','check_no','description','purchase_id'].includes(k)} value={form[k]??''} onChange={e=>setForm((x:any)=>({...x,[k]:e.target.value}))} type={k.includes('date')?'date':k.includes('amount')||['quantity','unit_price','purchase_id','opening_balance'].includes(k)?'number':'text'} className="mt-1 w-full rounded-xl border px-3 py-2"/></label>)}<button disabled={busy} className="rounded-xl bg-slate-900 py-3 font-bold text-white sm:col-span-2 lg:col-span-4">{busy?'در حال ثبت...':'ثبت اطلاعات'}</button></form><section className="mt-4 rounded-3xl bg-white p-5 ring-1 ring-slate-200"><div className="mb-3 flex justify-between"><h2 className="font-black">اطلاعات ثبت‌شده</h2><span className="text-xs text-slate-500">{rows.length.toLocaleString('fa-IR')} مورد</span></div>{loading?<p>در حال دریافت...</p>:rows.length===0?<p className="text-sm text-slate-500">هنوز موردی ثبت نشده است.</p>:<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{rows.map(r=><article key={r.id} className="rounded-2xl border p-4"><div className="flex justify-between"><b>{r.name||r.title||r.check_no||r.description||('شناسه '+r.id)}</b><button onClick={()=>del(r.id)} className="text-sm font-bold text-red-600">حذف</button></div><div className="mt-2 space-y-1 text-xs text-slate-600">{fields[type].filter((k:string)=>r[k]!==null&&r[k]!==undefined&&r[k]!=='').map((k:string)=><p key={k}><b>{pretty(k)}:</b> {['amount','opening_balance','unit_price'].includes(k)?money(r[k]):String(r[k])}</p>)}</div></article>)}</div>}</section></div></main>}
